name: motifcompendium
channels:
- conda-forge
- defaults
dependencies:
- python=3.10
- h5py
- leidenalg
- numpy
- pandas
- pytables
- seaborn
- scikit-learn
- tqdm
- jupyter
- pip
- pip:
    - beautifulsoup4
    - igraph
    - Jinja2
    - leidenalg
    - logomaker
    - upsetplot
    - gdown