name: motifcompendium-gpu
channels:
- nvidia
- conda-forge
- defaults
dependencies:
- python=3.10
- h5py
- jinja2
- numpy
- pandas
- tables
- seaborn
- scikit-learn
- pip
- pip:
    - cupy-cuda11x
    - cugraph-cu11
    - cudf-cu11
    - igraph
    - leidenalg
    - logomaker
    - upsetplot
